import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div>
      <Head>
        <title>iantxd 2k22</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid h-screen place-items-center">
        <div>
          <h1
            className="text-4xl md:text-6xl lg:text-8xl font-bold
              bg-gradient-to-r bg-clip-text  text-transparent
              from-sky-500 via-purple-500 to-indigo-500
              animate-text"
          >
            Antonio Orozco
          </h1>
          <div className="flex gap-2">
            <Image src="/assets/github.svg" className="cursor-pointer" height={50} width={50} />
            <Image src="/assets/twitter.svg" className="cursor-pointer" height={46} width={46} />
            <Image src="/assets/linkedin.svg" className="cursor-pointer" height={45} width={45} />
          </div>
        </div>
      </main>
    </div>
  );
}
